"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FaMicrophone } from "react-icons/fa";

import "./ChatBot.css";

import { projects } from "../../../data/projectData";

const logo = "/assets/logo/logo.png";



export default function ChatBot(){


    const defaultMessage = [

        {
            sender:"bot",
            text:"Hello 👋 Welcome to HydraNexa Energy. How can I help you?"
        }

    ];




    const [open,setOpen] = useState(false);

    const [input,setInput] = useState("");

    const [typing,setTyping] = useState(false);




    const [messages,setMessages] = useState(defaultMessage);

    // Load chat from localStorage on client side
    useEffect(()=>{
        if(typeof window !== 'undefined'){
            const savedChat = localStorage.getItem("hydranexa-chat");
            if(savedChat){
                setMessages(JSON.parse(savedChat));
            }
        }
    }, []);


    const quickQuestions=[

        "Our Projects",
        "Project Capacity",
        "Location",
        "Career",
        "Contact"

    ];








    // Voice Input

    const startVoice = ()=>{


        const SpeechRecognition =
        window.SpeechRecognition ||
        window.webkitSpeechRecognition;



        if(!SpeechRecognition){

            alert(
            "Voice input is not supported in this browser"
            );

            return;

        }



        const recognition =
        new SpeechRecognition();



        recognition.lang="en-US";


        recognition.start();



        recognition.onresult=(event)=>{


            const voiceText =
            event.results[0][0].transcript;


            setInput(voiceText);


        };
        const sendMessage = ()=>{
        // chatbot send logic
    };



    return(
        <div className="chatbot">

            {/* Your chatbot UI */}

        </div>
    );




    };

    // Chatbot Knowledge


    const generateReply=(question)=>{


        const text =
        question.toLowerCase();



        if(
            text.includes("hello") ||
            text.includes("hi") ||
            text.includes("namaste") ||
            text.includes("नमस्ते")
        ){

            return "नमस्ते 👋 Welcome to HydraNexa Energy. How can I assist you?";

        }

        if(
            text.includes("project")
        ){


            return (

`⚡ Our Hydropower Projects:


${projects.map(

(item)=>
`${item.name} - ${item.capacity}`

).join("\n")}`

            );

        }


        if(
            text.includes("capacity") ||
            text.includes("mw")
        ){


            return (

`⚡ Project Capacity:


${projects.map(

(item)=>
item.capacity

).join(", ")}`

            );

        }

        if(
            text.includes("location") ||
            text.includes("where")
        ){


            return (

`📍 Project Locations:


${projects.map(

(item)=>
item.location

).join("\n")}`

            );

        }



        if(
            text.includes("hydropower") ||
            text.includes("what is hydropower")
        ){


            return (

`Hydropower is renewable energy generated by using flowing water to produce electricity.`

            );

        }


        if(
            text.includes("generation") ||
            text.includes("electricity")
        ){


            return (

`Electricity is generated by converting water energy into mechanical energy using turbines and generators.`

            );

        }


        if(
            text.includes("turbine")
        ){


            return (

`A turbine converts water energy into mechanical energy which helps produce electricity.`

            );

        }



        if(
            text.includes("dam")
        ){


            return (

`A dam stores and controls water flow for efficient electricity generation.`

            );

        }


        if(
            text.includes("renewable") ||
            text.includes("clean energy")
        ){


            return (

`Hydropower is a clean and renewable energy source with low carbon emissions.`

            );

        }


        if(
            text.includes("environment") ||
            text.includes("sustainability")
        ){


            return (

`HydraNexa focuses on sustainable hydropower development and environmental responsibility.`

            );

        }



        if(
            text.includes("investment")
        ){


            return (

`Hydropower projects require investment in infrastructure, technology and construction.`

            );

        }

        if(
            text.includes("career") ||
            text.includes("job") ||
            text.includes("internship")
        ){


            return (

`You can visit HydraNexa Careers page for internship and job opportunities.`

            );

        }



        if(
            text.includes("contact") ||
            text.includes("email")
        ){


            return (

`You can contact HydraNexa through our Contact page.`

            );

        }


        if(
            text.includes("status") ||
            text.includes("progress")
        ){


            return (

`You can check project progress from our Projects section.`

            );

        }

        return (

`Sorry, I couldn't understand.

Please ask about:
Projects, Capacity, Location, Career, Contact or Hydropower.`

        );



    };



    // Send Message


    const sendMessage=(message=input)=>{


        if(!message.trim())
        return;




        setMessages(prev=>[

            ...prev,

            {
                sender:"user",
                text:message
            }

        ]);




        setInput("");

        setTyping(true);




        setTimeout(()=>{


            const reply =
            generateReply(message);



            setMessages(prev=>[

                ...prev,

                {
                    sender:"bot",
                    text:reply
                }

            ]);



            setTyping(false);



        },1000);



    };

    // New Chat


    const newChat=()=>{


        setMessages(defaultMessage);


        localStorage.removeItem(
            "hydranexa-chat"
        );


    };

    // Save Chat History


    useEffect(()=>{


        localStorage.setItem(

            "hydranexa-chat",

            JSON.stringify(messages)

        );


    },[messages]);

    return(


<div className="chatbot">

<motion.button

className="chat-toggle"


onClick={()=>setOpen(!open)}


animate={{

scale:[1,1.1,1]

}}


transition={{

duration:2,

repeat:Infinity

}}


>

💬

</motion.button>

{
open &&

<motion.div


className="chat-window"



initial={{

opacity:0,

y:40

}}

animate={{

opacity:1,

y:0

}}



>
<div className="chat-header">

<img

src={logo}

alt="HydraNexa"

className="chat-logo"

/>

<div>

<h4>
HydraNexa Assistant
</h4>


<span>
🟢 Online
</span>


</div>
<button

className="new-chat"

onClick={newChat}

>

New Chat

</button>

</div>
<div className="quick-buttons">


{

quickQuestions.map((item,index)=>(


<button

key={index}

onClick={()=>sendMessage(item)}

>

{item}

</button>


))

}



</div>
<div className="chat-body">


{

messages.map((msg,index)=>(


<div

key={index}

className={msg.sender}

>

{msg.text}

</div>


))

}

{

typing &&


<div className="bot">

Typing...

</div>


}



</div>

<div className="chat-footer">


<input

type="text"

placeholder="Ask something..."

value={input}


onChange={(e)=>setInput(e.target.value)}


onKeyDown={(e)=>{

if(e.key==="Enter")
sendMessage();

}}

/>

<button

className="voice-btn"

onClick={startVoice}

>

<FaMicrophone/>

</button>


<button

onClick={()=>sendMessage()}

>

Send

</button>


</div>


</motion.div>


}



</div>


    );

}
